stages:
  - build
  - deploy

build:
  stage: build
  image: node:16-alpine
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - ssh -i /key/LightsailDefaultKey-ap-southeast-1.pem ubunto@13.213.53.227 "cd /home/ubuntu/front/mongkol-serey-frontend && git pull"
