import { CustomerInput } from 'pages/Customer/CustForm/CustomerForm';

export interface ICustCard extends CustomerInput {
  id: number;
  profile: string;
  upComing: string;
  ordered: number;
  lastOrder: string;
  gift: number;
}
const customerCard: ICustCard[] = [
  {
    id: 1,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
  {
    id: 2,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
  {
    id: 3,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
  {
    id: 4,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
  {
    id: 5,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
  {
    id: 6,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
  {
    id: 7,
    profile: '',
    upComing: '2 Days',
    ordered: 3,
    lastOrder: '21-07-2022',
    gift: 3,
    customerName: 'abc',
    contact: '0987654328',
    facebook: 'abc',
    telegram: 'abc',
    houseNo: '21',
    stNo: '2004',
    location: 'Borey abc',
    province: 'Phnom Penh',
    district: 'Saen Sok',
    commune: 'Tek Tla',
  },
];
export { customerCard };
