import { IExpenseRow } from 'pages/Expense/ExpenseDialogs';

const listTitle: IExpenseRow[] = [
  {
    id: undefined,
    title: 'កម្លាំងចុងភៅ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ថ្លៃជួលសម្ភារៈ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ឡានដឹក',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ហ្គាស',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់ជ្រូក',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់ទា',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់គោ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់មាន់',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'គ្រឿងសមុទ្រ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់ពពែ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីឆ្ដោរ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីឆ្ដុង',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីតុកែ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីសុងហឺ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ជ្រូកខ្វៃ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ទាខ្វៃ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'បន្លែ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ប្រហិតបាក់សៀប ជើងទា',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ចាហួយ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'រោងកម្មវិធី',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'កម្រាលព្រំ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ក្ដាពិស',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'អំពូល កង្ហារ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'អំពូល គ្រីសស្ទាល់',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ម៉ាស៊ីនភ្លើង',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ចាប់ក្រណាត់មុខរោង',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សេវាពិធីការ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'នំបុ័ង',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ឆាខ្វៃ សណ្ដែក',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'បង្អែម',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីឆ្អើរ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ពងត្រី',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ទឹកកកអនាម័យ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'អង្ករ',
    totalPrice: 0,
    paidBy: '',
    other: '',
  },
];
const paidBy = [
  'ACLEDA',
  'ABA',
  'WING',
  'BAKONG',
  'CANADIA',
  'SATHAPANA',
  'WOORI',
  'TRUE MONEY',
  'AMK',
  'PRASAC',
  'PHILLIP',
  'PRINCE',
  'HATTHA',
  'CP Bank',
  'VATTANAC',
  'JTRUST ROYAL',
  'FTB Bank',
  'PPC Bank',
  'CHIP MONG Bank',
  'MOHANOKOR',
  'SBI LY HOUR',
  'MAY Bank',
  'eMoney Agent',
  'Pi Pay',
  'Cash',
];

const paidByColor = {
  ACLEDA: '#143c6d',
  ABA: '#005b7a',
  WING: '#a4c535',
  BAKONG: '#dc222c',
  CANADIA: '#D61229',
  'TRUE MONEY': '#F7F7F7',
  'Pi Pay': '#E62786',
};

const foodList = [
  'មហាសម្បត្តិទាំង៥',
  'ឆាប៉ាវហុឺ តៅហ៊ូពងមាន់ 10ក្រឡ',
  'ភ្លាម៉ាញ៉ាណេសាច់គោ ',
  'បង្គាបំពងខ្ទឹមស',
  'ត្រីឆ្ពុងចំហុយក្រូចឆ្មា ទឹកដោះគោឆៅ',
  'ម្ជូរយួនបង្កង',
  'បាយឆាគ្រាប់ឈូក & បាយស',
  'បង្អែមសងខ្យា3ស្រទាប់',
  'ក្ងានខ្វៃទឹកឃ្មុំ ទាខ្វៃប៉េកាំង',
  'ឆាផ្សិតតុងកូវ បន្លែបញ្ជះពណ៍',
  'ម្ជូរគ្រឿងពោះគោ',
  'បាយឆាពងទាប្រៃ & បាយស',
  'បង្អែមចេកខ្ទិះ ពងមាន់',
];

export { paidBy, paidByColor, listTitle, foodList };
