import { IExpenseRow } from 'pages/Expense/ExpenseDialogs';

const listTitle: IExpenseRow[] = [
  {
    id: undefined,
    title: 'កម្លាំងចុងភៅ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ថ្លៃជួលសម្ភារៈ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ឡានដឹក',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ហ្គាស',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់ជ្រូក',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់ទា',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់គោ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់មាន់',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'គ្រឿងសមុទ្រ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សាច់ពពែ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីឆ្ដោរ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីឆ្ដុង',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីតុកែ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីសុងហឺ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ជ្រូកខ្វៃ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ទាខ្វៃ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'បន្លែ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ប្រហិតបាក់សៀប ជើងទា',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ចាហួយ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'រោងកម្មវិធី',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'កម្រាលព្រំ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ក្ដាពិស',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'អំពូល កង្ហារ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'អំពូល គ្រីសស្ទាល់',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ម៉ាស៊ីនភ្លើង',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ចាប់ក្រណាត់មុខរោង',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'សេវាពិធីការ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'នំបុ័ង',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ឆាខ្វៃ សណ្ដែក',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'បង្អែម',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ត្រីឆ្អើរ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ពងត្រី',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'ទឹកកកអនាម័យ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
  {
    id: undefined,
    title: 'អង្ករ',
    totalPrice: '',
    paidBy: '',
    other: '',
  },
];
const paidBy = [
  'ACLEDA',
  'ABA',
  'WING',
  'BAKONG',
  'CANADIA',
  'SATHAPANA',
  'WOORI',
  'TRUE MONEY',
  'AMK',
  'PRASAC',
  'PHILLIP',
  'PRINCE',
  'HATTHA',
  'CP Bank',
  'VATTANAC',
  'JTRUST ROYAL',
  'FTB Bank',
  'PPC Bank',
  'CHIP MONG Bank',
  'MOHANOKOR',
  'SBI LY HOUR',
  'MAY Bank',
  'eMoney Agent',
  'Pi Pay',
  'Cash',
];

const paidByColor = {
  ACLEDA: '#143c6d',
  ABA: '#005b7a',
  WING: '#a4c535',
  BAKONG: '#dc222c',
  CANADIA: '#D61229',
  'TRUE MONEY': '#F7F7F7',
  'Pi Pay': '#E62786',
};

export { paidBy, paidByColor, listTitle };
