const listTitle = [
  'កម្លាំងចុងភៅ',
  'ថ្លៃជួលសម្ភារៈ',
  'ឡានដឹក',
  'ហ្គាស',
  'សាច់ជ្រូក',
  'សាច់ទា',
  'សាច់គោ',
  'សាច់មាន់',
  'គ្រឿងសមុទ្រ',
  'សាច់ពពែ',
  'ត្រីឆ្ដោរ',
  'ត្រីឆ្ដុង',
  'ត្រីតុកែ',
  'ត្រីសុងហឺ',
  'ជ្រូកខ្វៃ',
  'ទាខ្វៃ',
  'បន្លែ',
  'ប្រហិតបាក់សៀប ជើងទា',
  'ចាហួយ',
  'រោងកម្មវិធី',
  'កម្រាលព្រំ',
  'ក្ដាពិស',
  'អំពូល កង្ហារ',
  'អំពូល គ្រីសស្ទាល់',
  'ម៉ាស៊ីនភ្លើង',
  'ចាប់ក្រណាត់មុខរោង',
  'សេវាពិធីការ',
  'នំបុ័ង',
  'ឆាខ្វៃ សណ្ដែក',
  'បង្អែម',
  'ត្រីឆ្អើរ',
  'ពងត្រី',
  'ទឹកកកអនាម័យ',
  'អង្ករ',
];
const paidBy = [
  'ACLEDA Bank',
  'ABA Bank',
  'WING Bank',
  'BAKONG',
  'CANADIA Bank',
  'SATHAPANA Bank',
  'WOORI WON Bank',
  'TRUE MONEY ',
  'AMK',
  'PRASAC',
  'PHILLIP Bank',
  'PRINCE Bank',
  'HATTHA Bank',
  'CP Bank',
  'VATTANAC Bank',
  'JTRUST ROYAL Bank',
  'FTB Bank',
  'PPC Bank',
  'CHIP MONG Bank',
  'MOHANOKOR',
  'SBI LY HOUR Bank',
  'MAY Bank',
  'eMoney Agent',
  'Pi Pay',
  'Cash',
];
export { paidBy, listTitle };
